import type { Metadata } from "next";
import "./globals.css";
import { inter } from "./ui/fonts";
import Navbar from "./components/navbar/Navbar"; 
import styles from './layout.module.css';

export const metadata: Metadata = {
  title: "Django bnb",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <Navbar />
        <div className={styles.div}>
          {children}
        </div>
      </body>
    </html>
  );
}
